// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using MonoTouch.UIKit;

namespace WM
{
	public partial class GameResultsViewController : UIViewController
	{
		public GameResultsViewController (IntPtr handle) : base (handle)
		{
		}

        private void UpdateUI()
        {
            var displayText = new StringBuilder();
	        var list = GameResult.AllGameResults.ToList();
			list.Sort(SortSelector);
            foreach(var result in list)
            {
                displayText.AppendFormat("Score {0} ({1}, {2})\n", result.Score, result.End, result.Duration);
            }
            display.Text = displayText.ToString();
        }

        public override void ViewWillAppear(bool animated)
        {
            base.ViewDidAppear(animated);
            UpdateUI();
        }

        Comparison<GameResult> _sortSelector;

        public Comparison<GameResult> SortSelector
        {
            get { return _sortSelector ?? (_sortSelector = GameResult.CompareScoreToGameResult); }
	        set{

                _sortSelector = value;
                UpdateUI();
            }
        }

        partial void sortByDate()
        {
	        SortSelector = GameResult.CompareEndDateToGameResult;
        }

		partial void sortByScore()
        {
			SortSelector = GameResult.CompareScoreToGameResult;
		}

		partial void sortByDuration()
        {
			SortSelector = GameResult.CompareDurationToGameResult;
		}

        void setup()
        {
        }

        public override void AwakeFromNib()
        {
            setup();
        }


	}
}
