// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace WM
{
	public partial class CardChooserViewController : UIViewController
	{
		public CardChooserViewController (IntPtr handle) : base (handle)
		{
		}

        int _rank;

        public int rank
        {
            get { return _rank; }
            set {
                _rank = value;
                rankLabel.Text = rankAsString();
            }
        }
        public string suit
        {
            get
            {
                return suitSegmentedControl.TitleAt(suitSegmentedControl.SelectedSegment);
            }

        }


        partial void changeRank(NSObject sender)
        {
            var slider = (UISlider)sender;
            rank = (int)(slider.Value);

        }
                
        private static string [] rankarray = new [] { "?", "A", "2", 
            "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K" }; 
        
        public string rankAsString()
        {
            return rankarray[rank];
        }


        public override void PrepareForSegue(UIStoryboardSegue segue, NSObject sender)
        {
            base.PrepareForSegue(segue, sender);

            var id = segue.Identifier;
            var vc = segue.DestinationViewController as CardDisplayViewController;
            if (id == "ShowCard" && vc != null)
            {
                vc.rank = rank;
                vc.suit = suit;
                vc.Title = rankAsString() + suit;
            }

        }

	}
}
