// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace WM
{
	public partial class AttributedStringViewController : UIViewController
	{

		public AttributedStringViewController (IntPtr handle) : base (handle)
		{
		}

    
        NSAttributedString _text;
        public NSAttributedString Text { 
            get {
                return _text;
            }
            set {
                _text = value;

                if (textView != null)
                    textView.AttributedText = value;
            }
        }


        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            if (Text != null)
                textView.AttributedText = Text;
        }

    }
}
