// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace WM
{
	public partial class FlickrPhotoTVCCell : UITableViewCell
	{
        public FlickrPhotoTVCCell() : base (UITableViewCellStyle.Subtitle, Key)
        {
            // TODO: add subviews to the ContentView, set various colors, etc.
            TextLabel.Text = "TextLabel";
        }
        
		public FlickrPhotoTVCCell (IntPtr handle) : base (handle)
		{
		}

        public static readonly NSString Key = new NSString("Flickr Photo");
      

	}
}
