// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace WM
{
	public partial class GameResultsViewController : UIViewController
	{
		public GameResultsViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
